- name: Restart bluetooth
  systemd:
    name: bluetooth
    state: restarted

- name: Restart PulseAudio
  systemd:
    name: pulseaudio
    state: restarted
  when: "'pulseaudio' in ansible_facts.packages"
