# Nvidia Driver Handlers
- name: Rebuild initramfs
  command: mkinitcpio -P

- name: Update GRUB config
  command: grub-mkconfig -o /boot/grub/grub.cfg

- name: Restart display manager
  service:
    name: "{{ display_manager | default('sddm') }}"
    state: restarted
