- name: Install Hyprland and Dependencies
  become: true
  pacman:
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - wl-clipboard
      #- xwayland
      - rofi-wayland
      - egl-wayland
    state: present
    update_cache: true
#- name: Install Hyprland
#  command: |
#    paru -S --noconfirm hyprland-git
