---
- name: Install GDM
  become: true
  pacman:
    name:
      - gdm
    state: present
    update_cache: yes

- name: Install gdm-settings
  command: |
    paru -S gdm-settings


- name: Enable gdm
  become: true
  systemd:
    name: gdm
    enabled: yes
