- name: Update pacman db
  become: true
  command: |
    pacman-db-upgrade

- name: Update pacman
  become: true
  pacman:
    update_cache: true

- name: Make sure Pip is installed
  become: true
  pacman:
    name: python-pip
    state: present

- name: Install Python Requirements
  pacman:
    name:
      - python-passlib
    state: present

- name: Arch Configuration | Install Base Configs
  block:
    # Add the user
    - import_tasks: user/user.yaml

    # Run the base install files
    - import_tasks: system/base.yaml
    - import_tasks: networking/networkmanager.yaml
    - import_tasks: system/ssh.yaml
    - import_tasks: system/ufw.yaml
    - import_tasks: software/git.yaml
    - import_tasks: system/grub.yaml
    - import_tasks: system/paru.yaml
    - import_tasks: desktop_env/login_manager.yaml
    - import_tasks: system/nvidia.yaml
    - import_tasks: system/fonts.yaml
    - import_tasks: system/pipewire.yaml
    - import_tasks: networking/bluetooth.yaml

    # Start SDDM after everything is configured
    - name: Start SDDM (final step)
      systemd:
        name: sddm
        state: started

    # Run base system verifications
    - import_tasks: system/verification.yaml

  rescue:
    - set_fact: task_failed=true

- name: Arch Configuration | Install Desktop Environment
  block:
    - import_tasks: desktop_env/hyprland.yaml
    - import_tasks: desktop_env/thunar.yaml
    - import_tasks: desktop_env/waybar.yaml
    - import_tasks: desktop_env/widgets.yaml
    - import_tasks: desktop_env/wallpaper.yaml
    - import_tasks: desktop_env/clipboard.yaml
    - import_tasks: desktop_env/fuzzel.yaml
    - import_tasks: desktop_env/mako.yaml
    - import_tasks: desktop_env/hyprpolkitagent.yaml

- name: Arch Configuration | Install Devtools
  block:
    - import_tasks: software/wezterm.yaml
    - import_tasks: devtools/nodejs.yaml
    - import_tasks: devtools/ruby.yaml
    - import_tasks: devtools/rust.yaml
    - import_tasks: devtools/neovim.yaml
    - import_tasks: devtools/dotfiles.yaml

- name: Arch Configuration | Install Browsers
  block:
    - import_tasks: browser/librewolf.yaml
    - import_tasks: browser/zen_browser.yaml

    # Run browser verifications
    - import_tasks: browser/verification.yaml

- name: Arch Configuration | Install Cluster Tools
  block:
    - import_tasks: cluster/kubernetes.yaml
    - import_tasks: cluster/zot.yaml
    - import_tasks: cluster/spark.yaml

- name: Arch Configuration | Install Additional Software
  block:
    - import_tasks: software/gimp.yaml
    - import_tasks: software/inkscape.yaml
    - import_tasks: software/steam.yaml
