- name: Install LibreWolf
  pacman:
    name: librewolf
    state: present

- name: Deploy LibreWolf policies
  copy:
    content: |
      {
        "policies": {
          "DisableTelemetry": true,
          "DisablePocket": true,
          "Extensions": {
            "Install": [
              "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
              "https://addons.mozilla.org/firefox/downloads/latest/bitwarden/latest.xpi"
            ]
          }
        }
      }
    dest: /usr/lib/librewolf/distribution/policies.json
    mode: "0644"
  become: yes

- name: Configure user.js
  template:
    src: templates/librewolf_user.js.j2
    dest: "~/.librewolf/{{ ansible_user_id }}/profiles/default/user.js"

- name: Install uBlock Origin
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi
    dest: "~/.librewolf/{{ ansible_user_id }}/extensions/uBlock0@raymondhill.net.xpi"

- name: Fetch Bitwarden extension ID
  uri:
    url: https://addons.mozilla.org/api/v4/addons/addon/bitwarden-password-manager/
    return_content: yes
  register: bitwarden_info

- name: Install Bitwarden
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/file/{{ bitwarden_info.json.current_version.file.id }}/"
    dest: "~/.librewolf/{{ ansible_user_id }}/extensions/{446900e4-71c2-419f-a6a7-df9c091e268b}.xpi"

- name: Create custom profile
  command: |
    librewolf -CreateProfile "WorkProfile /home/{{ ansible_user_id }}/.librewolf/work_profile"
  args:
    creates: "~/.librewolf/work_profile"
