# Install Zen Browser from AUR
- name: Install Zen Browser
  paru:
    name: zen-browser-bin
    state: present
  tags: install

# Basic config file creation
- name: Ensure config directory exists
  file:
    path: "~/.config/zen-browser"
    state: directory
  tags: config
