# Git Identity
git_identity:
  name: "Geoff Groenendale"
  email: "g.groenendale@gmail.com"

# Nvidia Configuration
# For SDDM (KDE)
display_manager: sddm
# For GDM (GNOME)
# display_manager: gdm

# For LightDM (XFCE/LXDE)
# display_manager: lightdm

# Run verification tasks
verify_enabled: true

# Apps to enable install for
desktop_apps:
  freecad: true
  gimp: true
  inkscape: true
  steam: true
