# Debian Main Config
#
# This file should orchestrate all of the tasks that need to run for the Debian
# Server install in a sensible order. Such as loading and installing basic packages
# then configuring netork management, then as a later step setting up the NAS stuff
# like LVM and Samba.
#
- name: Debian Configuration | Install Base Configs
  block:
    # Run the base install files
    - import_tasks: system/base.yaml

- name: Debian Configuration | Install Network Management
  block:
    - import_tasks: networking/base.yaml

- name: Debian Configuration | Configure NAS Storage
  block:
    - import_tasks: nasdrive/mdadm.yaml
    - import_tasks: nasdrive/lvm.yaml
    - import_tasks: nasdrive/samba.yaml
