# Bluetooth Verification steps
- name: Check Bluetooth status
  command: bluetoothctl show
  register: bt_status
  changed_when: false
  failed_when: "'Controller' not in bt_status.stdout"

- name: Verify devices
  command: bluetoothctl devices
  register: bt_devices
  changed_when: false
