- name: Install Neovim
  become: true
  pacman:
    name:
      - neovim
      - ripgrep
    state: present

- name: Install Lazygit
  become: true
  pacman:
    name:
      - lazygit
    state: present
