- name: Ensure installation directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /usr/local/bin
    - /usr/local/lib/gcm-core

- name: Download GCM artifacts
  block:
    - get_url:
        url: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-linux_amd64.2.6.1.tar.gz
        dest: /tmp/gcm.tar.gz

    - get_url:
        url: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-linux_amd64.2.6.1.tar.gz.asc
        dest: /tmp/gcm.tar.gz.asc

    - get_url:
        url: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-public.asc
        dest: /tmp/gcm-public.asc

- name: Import GCM public key
  command: gpg --import /tmp/gcm-public.asc

- name: Verify GCM tarball
  command: gpg --verify /tmp/gcm.tar.gz.asc /tmp/gcm.tar.gz

- name: Install GCM
  become: true
  unarchive:
    src: /tmp/gcm.tar.gz
    dest: /usr/local/bin/
    creates: /usr/local/bin/git-credential-manager
