# Regular Configuration tasks
- name: Configure ArchLinux Git
  include_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Configure Debian Git
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Run Verification Tasks
  include_tasks: ../verify/main.yaml
  when: verify_enabled | default(false)
