# This configuration sets up backup storage for btrfs backups and other system backups
#

- name: Create Folders for btrfs backups
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /srv/backupdisk/arch-desktop
    - /srv/backupdisk/arch-laptop
    - /srv/backupdisk/debian-server
