# Install mdadm
#
# This is necessary for ensuring the server can utilize Raid and access the raid that is on the drives I will use

- name: Install mdadm
  apt:
    name: mdadm
    state: present

- name: Assemble all detected RAID arrays
  command: mdadm --assemble --scan
  register: mdadm_result
  changed_when: "'No arrays found' not in mdadm_result.stdout"

- name: Persist mdadm config (optional but useful)
  command: mdadm --detail --scan
  register: mdadm_scan

- name: Write mdadm.conf from scanned arrays
  copy:
    dest: /etc/mdadm/mdadm.conf
    content: |
      DEVICE partitions
      {{ mdadm_scan.stdout }}
  when: mdadm_scan.stdout != ""
