- name: Install Samba
  apt:
    name: samba
    state: present
    update_cache: true

- name: Copy custom smb.conf
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart samba

- name: Create Samba shared directory
  file:
    path: "{{ samba_share_path }}"
    state: directory
    owner: "{{ samba_user }}"
    group: "{{ samba_user }}"
    mode: "0775"

- name: Set Samba password for user
  command: "echo -ne '{{ samba_password }}\n{{ samba_password }}\n' | smbpasswd -a {{ samba_user }}"
  args:
    creates: "/var/lib/samba/private/passdb.tdb"
  when: samba_password is defined

- name: Enable and start smbd
  systemd:
    name: smbd
    enabled: true
    state: started
